import React from 'react';

export const Terms: React.FC = () => {
  return (
    <div className="max-w-screen-lg mx-auto px-6 md:px-12 py-12 animate-fade-in-up min-h-screen">
      <div className="mb-16 text-center">
        <span className="text-xs font-bold uppercase tracking-widest text-stone-400 mb-2">Legal</span>
        <h2 className="font-serif text-4xl md:text-5xl text-stone-900 mb-6">Terms of Service</h2>
        <p className="text-stone-500">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
      </div>

      <div className="space-y-12 text-stone-600 font-light leading-relaxed">
        <section>
          <h3 className="font-serif text-2xl text-stone-900 mb-4">1. Acceptance of Terms</h3>
          <p>
            By accessing and using StyleSync AI, you accept and agree to be bound by the terms and provision of this agreement. In addition, when using this websites particular services, you shall be subject to any posted guidelines or rules applicable to such services.
          </p>
        </section>

        <section>
          <h3 className="font-serif text-2xl text-stone-900 mb-4">2. Description of Service</h3>
          <p>
            StyleSync AI provides users with AI-powered fashion styling recommendations based on uploaded images. You understand and agree that the Service may include certain communications from StyleSync AI, such as service announcements and administrative messages.
          </p>
        </section>

        <section>
          <h3 className="font-serif text-2xl text-stone-900 mb-4">3. User Conduct</h3>
          <p className="mb-4">
            You agree to not use the Service to:
          </p>
          <ul className="list-disc pl-5 space-y-2 marker:text-stone-400">
            <li>Upload any content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable.</li>
            <li>Harm minors in any way.</li>
            <li>Impersonate any person or entity.</li>
            <li>Upload any content that you do not have a right to make available under any law or under contractual or fiduciary relationships.</li>
          </ul>
        </section>

        <section>
          <h3 className="font-serif text-2xl text-stone-900 mb-4">4. Intellectual Property</h3>
          <p>
            The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of StyleSync AI and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.
          </p>
        </section>

        <section>
          <h3 className="font-serif text-2xl text-stone-900 mb-4">5. AI Disclaimer</h3>
          <p>
            The outfit recommendations and images generated by our AI are for inspirational purposes only. StyleSync AI does not guarantee the availability, price, or exact match of any items depicted in generated images. The generated content is synthetic and created by artificial intelligence.
          </p>
        </section>

        <section>
          <h3 className="font-serif text-2xl text-stone-900 mb-4">6. Termination</h3>
          <p>
            We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
          </p>
        </section>
      </div>
    </div>
  );
};